general {
    col.active_border = rgba(E5383BFF) rgba(E76F8BFF) 45deg
    col.inactive_border = rgba(2D2D4AFF)
}

decoration {
    shadow {
        color = rgba(0F0F1A99)
    }
}

group {
    col.border_active = rgba(E5383BFF) rgba(E76F8BFF) 45deg
    col.border_inactive = rgba(2D2D4AFF)

    groupbar {
        col.active = rgba(E5383BFF)
        col.inactive = rgba(1A1A2EFF)
        text_color = rgba(EDF2F4FF)
    }
}
